### ISSUE TITLE
能把这个库提交到 bootcdn 之类的 cdn 吗？

### ISSUE THREAD

**Issue by sljeff** [weizhenye/Danmaku#10]
因为要引用这个库，而 greasefork 规定脚本里只能 require 它认为安全的 CDN 收录的库，不然不能提交。

所以我在 https://greasyfork.org/zh-CN/scripts/27239 这个脚本里直接复制了代码（我看到 MIT 协议写是可以复制代码的，但是如果觉得直接复制不妥的话我就会删掉）

**Comment by weizhenye** [comment]
看了下 [Greasy Fork 的规定](https://greasyfork.org/zh-CN/help/external-scripts)，它允许 RawGit 指定了 commit 的链接，那应该可以使用 `https://cdn.rawgit.com/weizhenye/Danmaku/93665a4c/dist/danmaku.min.js`，之后 Danmaku 如果有更新你需要手动更新下。

**Comment by sljeff** [comment]
THX！用 Rawgit 成功了。

但是它要求有明确的 commit 号，所以最后引用的是： `https://cdn.rawgit.com/weizhenye/Danmaku/b2ae44f7dcd28b27c31e5db5b512b9474d0396c7/dist/danmaku.min.js`

**Comment by weizhenye** [comment]
还有 [BowerCDN](https://bowercdn.net/package/danmaku) 应该也能用。

另外看了下 cdnjs，它要求项目至少 100 star，目前没办法了。
