### ISSUE TITLE
弹幕很长的时候反而速度很快导致看不清楚

### ISSUE THREAD

**Issue by superdiy** [weizhenye/Danmaku#13]
你好！

我用的DOM方式，使用时发现弹幕内容比较长的时候反而速度更快，快到都看不清楚。
但如果降低初始化速度，弹幕内容短的又太慢了。
我尝试修改脚本中的计算公式，但延长了长弹幕的生存时间又导致了后来的弹幕将其覆盖。

敬请赐教，谢谢！

**Comment by weizhenye** [comment]
Danmaku 实现的算法是传统的弹幕行为，从 niconico 到 AcFun 到 Bilibili，都是采用存活时间确定的方式，越长的弹幕是会越快的，这个行为就是这么设计的。

**Comment by superdiy** [comment]
非常感谢回答，原来是我对弹幕的理解有问题。
最后还是用在H5项目上了！再次表示感谢！
