### ISSUE TITLE
custom canvas painter

### ISSUE THREAD

**Issue by klouskingsley** [weizhenye/Danmaku#14]
In canvas mode, danmaku just stroke and fill the text, but in many scenes, there is a need to draw some other element, like image, rectangle, triangle...

Can we add a `paint` function in `cmt` which can custom the canvas draws like this:

```js
danmaku.emit({
  width: 50,
  height: 50,
  paint: function (ctx) {
    ctx.drawImage(img, 0, 0)
  }
 })
```

and in `commentCanvas.js`: 
```js
  if (typeof cmt.paint === 'function') {
    cmt.paint(ctx);
  } else {
    if (style.strokeStyle) {
      ctx.strokeText(cmt.text, strokeWidth, baseline);
    }
    ctx.fillText(cmt.text, strokeWidth, baseline);
  }
```

**Comment by weizhenye** [comment]
The `render` option of emit API is available in `v1.3.0`, you can find details in README.
