### ISSUE TITLE
能不能不显示历史的弹幕

### ISSUE THREAD

**Issue by coolicer** [weizhenye/Danmaku#15]
如果是实时的弹幕，你切换到其他tab，回来的时候感觉有一堆弹幕。

**Comment by weizhenye** [comment]
目前你可以使用 [Page Visibility API](https://developer.mozilla.org/zh-CN/docs/Web/API/Page_Visibility_API) 监听页面是否可见，然后自行调用 `danmaku.clear()` 清屏。

等我有空去了解下浏览器的非激活态的运行机制后再考虑是否将其作为默认行为。

**Comment by coolicer** [comment]
好的

**Comment by coolicer** [comment]
我在不可见时掉了clear方法，好像还是会有积累的时候。

**Comment by weizhenye** [comment]
在可见的时候调用 clear

**Comment by coolicer** [comment]
@weizhenye 
弹幕积累起来是浏览器的行为吗，我在代码中也看不到在哪

**Comment by coolicer** [comment]
好像是因为在切换到其他tab之前，已经加到了runningList中？

**Comment by weizhenye** [comment]
https://developers.google.com/web/updates/2017/03/background_tabs

页面不可见时 requestAnimationFrame 频率降到一秒一次，还没细看，还不清楚 engine 的文件里每行代码执行的频率。

**Comment by coolicer** [comment]
https://github.com/MoePlayer/DPlayer/blob/master/src/js/danmaku.js

你看他这个实现，应该不会有积累的问题的

**Comment by coolicer** [comment]
其实就是在hidden的时候还不断地emit数组导致，我在hidden的时候就return了，好像解决了。

**Comment by weizhenye** [comment]
研究了一下，是我的冲突检测算法写错了，`v1.3.1` 已经修复，现在不需要手动 clear 了。

**Comment by coolicer** [comment]
@weizhenye 想问一下，如果滚动了到下面，再回去，弹幕会不会积累。突然想到这个

**Comment by coolicer** [comment]
我发现旧版是会的，我还没升级。

**Comment by weizhenye** [comment]
如果某一时刻弹幕数量很多，已经排满一屏了，之后的弹幕会从顶部开始排，相当于直接拿容器高度取模。这个是传统的弹幕行为，就是这么设计的。

**Comment by coolicer** [comment]
@weizhenye 我没表达清楚，我的意思是滚动页面到底部，再滚回弹幕的区域，会不会千万累积

**Comment by weizhenye** [comment]
没想明白为什么滚动出屏后会有这个情况，难道也会导致 raf 频率降低？如果是有关 raf 的话，应该是已经修复了的。我试了下似乎是没有积累。

**Comment by coolicer** [comment]
难怪有点似曾相识，这个bug好像还会出现。
