### ISSUE TITLE
live mode下我暂停字幕能调pause那个api吗？

### ISSUE THREAD

**Issue by coolicer** [weizhenye/Danmaku#16]
视频暂停时，字幕能停下来吗？

**Comment by coolicer** [comment]
好像只有设置video就可以了，我试试

**Comment by coolicer** [comment]
我是用container来做显示容器， 这样的话，是不是它就不知道this.media了？

**Comment by weizhenye** [comment]
你的场景是什么？你的 video 是普通视频吗？

**Comment by coolicer** [comment]
@weizhenye 我的播放器是用了video.js，我在里面insert了一个div，要来放弹幕。所以video标签和div是同一个层级。看了你的代码，好像不能同时设container和video ?

**Comment by coolicer** [comment]
我为了方便，直接把play和pause挂到了window上，就算是留下一个坑吧。

**Comment by coolicer** [comment]
顺便再问，这个有没有弹道的实现？

**Comment by weizhenye** [comment]
你的 video 标签是普通的 mp4 之类的视频还是视频流？如果是普通的视频，container 和 video 是可以一起设置的，play 和 pause 自动从视频同步。

**Comment by coolicer** [comment]
@weizhenye videojs会自动选flash和video播放，所以不太确定。视频可以是普通的，也会放实时推的。

**Comment by weizhenye** [comment]
Danmaku 当时设计的行为是，<video> 或 <audio> 这样有时间轴的自动同步；直播这样无时间轴概念的，不提供播放暂停的控制。

对于普通的视频，指定好 video 元素就可以了，Flash 是不支持的，我不清楚会不会有其他不使用 video 元素播放的情况。

对于直播等情况，给一个无时间轴的对象加上播放暂停这样的时间轴的控制，感觉是比较怪的。如果有合理的场景，我之后可能会开放 play 和 pause 方法出来。

**Comment by coolicer** [comment]
额，其实我也觉得很傻，直播不应用暂停弹幕，但是同事要求，只要这样了。
