### ISSUE TITLE
连接websocket时，有大量的弹幕怎么优化？

### ISSUE THREAD

**Issue by coolicer** [weizhenye/Danmaku#17]
ws会不断地推数据，然后前端就不会地调emit方法，看了一下源码，每次emit就是push到comments，然后就没有利用到fragment，因为每次emit过来只有一条。。。

没有想到方法，我本来是想在emit的时候push到一个临时的数组，用setTimeout去计时，比如等100ms后，应该会有插入几十条，我再把它push，就可以利用上fragment。但是不行，不知道哪里有问题。

**Comment by weizhenye** [comment]
emit 方法是同步的，一个 for 去 emit 一组弹幕，会阻塞当前 rAF，然后在下一帧去使用 DocumentFragment 同时添加到 DOM 里。你的方法，每隔 100ms 同时插入若干弹幕，我测试出来是没问题的。

弹幕特别多的情况，如果没有另外的策略去限制数量而要全部显示出来的话，可以使用 canvas 模式，会比 DOM 模式性能高一点。

**Comment by coolicer** [comment]
@weizhenye 我现在的做法是让后端传一个array出来，然后循环push到this.comments，当然 还是兼容之前单个的评论。理论上能应用DocumentFragment的

**Comment by weizhenye** [comment]
你自己 push 和调用 emit 其实是一样的，只是 emit 多了校验格式化字段的步骤。我测试的结果，循环调用 emit，是会用到 DocumentFragment 的。

**Comment by coolicer** [comment]
哦。好的

**Comment by coolicer** [comment]
@weizhenye 我回放视频的时候，按时间取弹幕，每次都直接push到comments吗？我能不能直接`this.comments = res.data`

**Comment by coolicer** [comment]
最后再有一个棘手但又不重要的问题，视频在拖动的时候，就是onseek事件，会拿到一个区间内的弹幕，然后第一行分配好像有点问题，第一行最前面会叠起来一些，跑过一屏好像就正常。然后再拖进度条，还是会出现。

**Comment by weizhenye** [comment]
https://github.com/weizhenye/Danmaku/blob/master/src/api/emit.js 文件中还设置了 `cmt._utc` 。你不要自己操作 `danmaku.comments` 数组，用 `danmaku.emit` 方法，支持 fragment 优化的。

**Comment by coolicer** [comment]
@weizhenye 是录播的，有time字段的

**Comment by weizhenye** [comment]
**不要自己操作 `danmaku.comments` 数组**

你打开 https://danmaku.js.org/ ，找个 B 站弹幕加载进来，控制台输入 `for(let i = 0; i < 10; i++) videoDanmaku.emit({ time: 3, text: 'foo' })`，没问题的。

如果你一次性 emit 很多 time 相同的弹幕，根据经典的弹幕行为，排满一屏后会从上到下叠加上去，这个是正常的，但也不是你描述的第一行重叠的情况。
