### ISSUE TITLE
render没成功

### ISSUE THREAD

**Issue by mileOfSunshine** [weizhenye/Danmaku#20]
JSON.parse(JSON.stringify(json)) 会造成render方法丢失。

**Comment by weizhenye** [comment]
`JSON.parse` 和 `JSON.stringify` 只能处理 JSON，JavaScript 函数用这个去处理本来就是不能用的。

**Comment by mileOfSunshine** [comment]
是的。但是我看了您的源码，你用这两个函数对传入的数据进行处理了，这样的话，render函数丢失了。

**Comment by mileOfSunshine** [comment]
this.comments = JSON.parse(JSON.stringify(opt.comments || []));

就是源码里的上面这行代码。
