### ISSUE TITLE
切到别的标签页再返回时，期间的弹幕会一次全部显示出来

### ISSUE THREAD

**Issue by freekami** [weizhenye/Danmaku#21]
感谢制作这个很好用的库！
使用中遇到一个小问题，如果切到别的标签页一段时间再返回，离开期间的所有弹幕会一起显示出来。当前使用的是dom engine，以及最新版本的chrome。
加了一些console log发现，emit是有按照真实的时间触发，但是domEngine会在中间某个时间点停止并在切回标签页之后重新触发，然后一次跑完comments array的loop。
请问是否有办法处理这个问题呢？

-------
补充：多研究了一下发现应该是requestAnimationFrame在切换标签的时候停止了。那么有没有办法跳过这部分已经错过的弹幕呢？

**Comment by weizhenye** [comment]
这个问题 #15 讨论过，在版本 `v1.3.1` 应该已经修复了，你用的是最新版本吗？

**Comment by freekami** [comment]
是用的最新版呢，昨天刚下载的。

**Comment by weizhenye** [comment]
能提供可复现的代码吗？在 https://danmaku.js.org/ 里是没这个问题的

**Comment by freekami** [comment]
在codepen上做了一个demo：https://codepen.io/freekami/pen/wmZzRr
引用的js地址是https://cdn.rawgit.com/weizhenye/Danmaku/master/dist/danmaku.min.js，因为git raw版本mime type的问题，使用的替代地址，内容是一样的。感谢~

**Comment by freekami** [comment]
发现另一个问题喔， #9 提到这个，这次遇到的场景是直播弹幕。如果两条弹幕时间相近，正好显示在一排，而前一条比较短的话，这两条就会从大概中间位置开始重叠。

**Comment by weizhenye** [comment]
@freekami 实时模式切标签页堆叠的问题在 `v1.3.3` 修复了。

弹幕时间相近导致重叠的问题，需要给出复现代码，建议另开一个 issue

**Comment by freekami** [comment]
@weizhenye 感谢修复！不过在同一个codepen demo测试会看到刚切换回来时，开始的几条弹幕会有重叠现象。
另一个问题我看看怎么建一个demo再开新issue，感谢啦
