### ISSUE TITLE
弹幕时间相近会导致重叠

### ISSUE THREAD

**Issue by haina-x** [weizhenye/Danmaku#22]
如果两条弹幕时间相近，正好显示在一排，而前一条比较短的话，这两条弹幕就会从大概中间位置开始重叠。Demo: https://codepen.io/freekami/pen/xWvxWR
谢谢！

**Comment by weizhenye** [comment]
感谢 debug，这个问题是 71a56a7eb304b5cdc77731ffbb339d94e61de1c3 引入的，现在 `v1.3.4` 修复了。另外 #21 里后来提到的问题也是这个引起的。
