### ISSUE TITLE
是否支持在非视频/音频元素上显示弹幕呢？

### ISSUE THREAD

**Issue by Lxxyx** [weizhenye/Danmaku#25]
库很好用，谢谢作者，但是目前看到这个库只支持视频音频，可以改成支持任意元素吗？

**Comment by weizhenye** [comment]
未指定音视频而只指定 container 时就是实时模式，container 是用户自己传的，你可以把 container 覆盖在你想要的元素上。

**Comment by Lxxyx** [comment]
Get，谢谢
