### ISSUE TITLE
请问视频播放全屏弹幕不显示

### ISSUE THREAD

**Issue by hsj-xiaokang** [weizhenye/Danmaku#26]

**Comment by weizhenye** [comment]
`<video>` 元素自带的全屏按钮，只会把它本身给全屏了，包在视频外面的弹幕那层的 div 不会被全屏。

在实际使用中，通常会用 `video.js` 之类的库，它们的全屏是通过调用对应方法把整个 div 给全屏了。

在使用 Danmaku 的时候，需要自行调用全屏方法，进入全屏的元素内部要包含弹幕的 container。
