### ISSUE TITLE
是否可以让某一个弹幕对齐顶部或底部

### ISSUE THREAD

**Issue by Qquanwei** [weizhenye/Danmaku#27]
实现类似公告的效果，让某些重要的弹幕永远对齐在顶部。

**Comment by weizhenye** [comment]
如果是要长期不消失的弹幕，那直接自己写个 div 覆盖在 container 上就好了；如果要和普通弹幕相同的存活时间，DOM 引擎可以通过 style 里设置 `translateY` 和 `z-index` 实现，Canvas 引擎大概没办法。

**Comment by weizhenye** [comment]
你是需要在顶部滚动的弹幕？还是顶部静止的弹幕？

如果是要顶部的滚动，那你说的碰撞是指什么的碰撞？

我感觉，如果要让「公告」这种弹幕显示在顶部，那应该就是要覆盖其他普通弹幕的，然后你可以从样式上对公告和普通弹幕作区分。

**Comment by Qquanwei** [comment]
???????????????????Zhenye Wei <notifications@github.com>?2018?12?6? ????10:40??????????????????????????
????????????????????????
???????????????????????????????????????????????????????????

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Qquanwei** [comment]
了解了，我一开始想的可能有问题，我试试。
