### ISSUE TITLE
滚到底部，再回到弹幕区第一行堆起来了

### ISSUE THREAD

**Issue by coolicer** [weizhenye/Danmaku#28]
直播模式：弹幕在上面，滚到页面底部一段时间，回去看第一行有些弹幕会重叠。
好像在1.3.1我有提过这个问题

**Comment by weizhenye** [comment]
你用的是什么版本？在 #21 #22 修复过实时模式相关的问题，现在还有问题吗？能构造出可复现的 demo 吗？

**Comment by coolicer** [comment]
@weizhenye 我小改了点点东西，但是应该是对着1.3.5改的。
demo在本地，我不知道怎么弄。我在本地模拟推弹幕，只要往下滚，再回，第一条就会叠很多。好像只有第一行。
<img width="936" alt="WX20190425-100751@2x" src="https://user-images.githubusercontent.com/811078/56705059-06bc0a80-6742-11e9-835e-09fbc687a7e3.png">

**Comment by coolicer** [comment]
1.3.5
`cmt._utc = dn - (this.media.currentTime - cmt.time);`
这里跟之前版本不同？

**Comment by coolicer** [comment]
我好像找到问题了。cmt.y的值在滚动的时候，一直为0.
![image](https://user-images.githubusercontent.com/811078/56714293-f9654700-6766-11e9-8b1f-175724f38b46.png)

**Comment by coolicer** [comment]
是我自己的问题。小窗模式，我把container隐藏起来了
