### ISSUE TITLE
Canvas 渲染模式下不支持自定义"font-style"和"font-weight"

### ISSUE THREAD

**Issue by ShadeShady** [weizhenye/Danmaku#29]
CSS Font 属性的[规范](https://developer.mozilla.org/zh-CN/docs/Web/CSS/font)里提到 

> font-style, font-variant 和 font-weight 必须在 font-size 之前
```
canvasStyle: {
    font: 'italic bold 25px sans-serif'
}
```
但是这样设置之后就会出现高度计算不正常的问题，导致字体被截断。
![Snipaste_2019-12-12_22-32-52](https://user-images.githubusercontent.com/39401388/70721028-e58b4700-1d2f-11ea-9d2e-b285513d6fcf.png)

**Comment by weizhenye** [comment]
released in `v1.3.6`
