### ISSUE TITLE
canvas滚动帧数不够啊 

### ISSUE THREAD

**Issue by a1018148046** [weizhenye/Danmaku#3]

**Comment by weizhenye** [comment]
你测试了哪个弹幕文件？机器配置？帧数有多少？

**Comment by a1018148046** [comment]
随便找了b站视频测试的 帧数低是肉眼体验 比dom低多了。。。

**Comment by weizhenye** [comment]
![qq 20160902192531](https://cloud.githubusercontent.com/assets/1879224/18202527/193f7cca-7143-11e6-9a8a-aeedb53012f7.png)
图为 [New Game! 第八集](http://www.bilibili.com/video/av5976369/) 01:15 左右
像这样弹幕叠个三四层保持 60fps 是毫无压力的，DOM 引擎也一样，一直是 60fps
B 站的弹幕文件有条数限制，所以基本上拿 B 站来测试都是 60fps 的。
至于你说的肉眼差异，我看不出来。

**Comment by a1018148046** [comment]
抱歉 没弄清楚你脚本的原理就发言了 因为其他html5弹幕项目用的方式和你不同 帧数肉眼看起来比你高 但是cpu占用比你大 希望日后继续优化帧数吧。。。。肉眼上都比不上其他项目的方式(ps:我显示器144hz 习惯了高帧数)

**Comment by weizhenye** [comment]
倒是真没想过高帧数显示屏的问题。但我目前还没高帧数显示器，暂时没法测试。

弹幕重绘是使用 requestAnimationFrame 的，每一帧计算屏上各弹幕新的位置并重绘。
至于视频播放速度增加使弹幕帧数增加，这个理论上应该是无关的，还不知道原因。

有一个疑问：对于 144hz 的显示器，rAF 被调用的频率是每秒 144 次吗？如果浏览器是根据显示器频率来改变 rAF 的频率，那同时接了多台不同帧数的显示器会怎样？

可以请你提供一下各浏览器的性能分析数据吗？数据文件发我邮箱 weizhenye#gmail.com 或传网盘。
找个同屏弹幕较多的时间段，录制个 10 秒左右。
Chrome DevTools 中的 Timeline，在视频播放后点击左上角 Record 按钮，录完后右键 Save Timeline Data。顺便右上角三个点的 Customize and control DevTools 按钮，More tools -> Rendering settings，下面弹出的 drawer tabs 中 FPS Meter 打勾可以看到实时的 FPS。
Firefox 和 Edge 类似，F12 后都有性能选项，录制后可以保存数据文件。

**Comment by a1018148046** [comment]
数据文件今晚提供网盘 不过我还是好奇为啥视频播放速度提升会让弹幕的帧数明显感受提升 你的源码看了半天不知道怎么回事……希望大神你能研究出为什么了 视频加速后弹幕肉眼感觉帧数高（f12性能那里平均帧数居然一样） cpu占用也没变高 这应该是一个优化点

**Comment by a1018148046** [comment]
http://i1.piimg.com/567571/ed1a8ee9e4537f6b.jpg
经过测试确实是因为currentTime的刷新率不是60hz啊。。。调用requestAnimationFrame获取currentTime插入数组 结果是上图数组
链接: http://pan.baidu.com/s/1i57BtOT 密码: nfg4 这是某b站视频的dom模式性能数据

**Comment by weizhenye** [comment]
原来如此。rAF 帧数是没问题，只是相邻的两个 rAF 在计算位置时由于 currentTime 没变导致位置也没变，所以看上去帧数不够（虽然我看不出来

currentTime 改变会触发 timeupdate 事件，根据 [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/timeupdate) 描述似乎顶天也就 66Hz 了。

实时模式是根据 `Date.now()` 来计算的，应该不会有这个问题，你可以试一下。

晚点我会把 video 和 audio 模式都改成 `Date.now()` 的。

另外，为了减少脚本计算时间，我把计算后的位置值都取整了，不知道这个对肉眼帧数影响大不大，可能非高分屏都表现不出小数点的移动变化吧。

**Comment by a1018148046** [comment]
屏幕dpi越低才越明显吧。。。。我自己这边改了下用Date.now() 还是略有弹幕瞬移 取整应该也有影响 话说你dom模式为什么不用css动画呢。。。是不是以前测试css动画占用太高

**Comment by weizhenye** [comment]
低分屏，假如一开始显示 23，然后要显示 23.3，但肉眼看上去 23 和 23.3 没有差别，屏幕表现不出来，但这是屏幕极限了，对其没影响；高分屏下最小步长为 1px 的话，没有达到屏幕极限，对其有影响。

CSS 动画我还没找到一个完美的方案。先不说它不支持 IE9，keyframes 规则要求知道起始与结束的状态，而每条弹幕的长度都是不同的，那就要为每条弹幕都生成一条 keyframes 规则。而 keyframes 规则没法通过 JS 直接去设置，只能生成 CSS 字符串添加到 `<style>` 中去，此时就有一个浏览器解析字符串的脚本时间，keyframes 规则多了之后这个脚本时间也是会增加的。目前的 DOM 方式 JavaScript 动画每次改变 transform 属性，这部分的脚本时间与 CSS 相比还不清楚。CSS 动画可以启用硬件加速，JavaScript 动画也可以启用硬件加速。从时间消耗上看，两者效率我猜应该是差不多的，当然我没有做过完整的测试，具体结果还不清楚。我有看到[文章](https://davidwalsh.name/css-js-animation)说 JS 可以比 CSS 更快，但它没讲具体原理，实际怎样还是要测试后才知道。

我的另一个项目 [ASS.js](https://github.com/weizhenye/ASS) 的动画效果是用 CSS Animation 实现的，你可以用 [danmaku2ass](https://github.com/m13253/danmaku2ass) 之类的把弹幕文件转化成 ASS 文件试一下，不过 ASS.js 的性能肯定比不上专门为弹幕优化的 Danmaku，大致可以感受一下。
我原来以为每次改变 `<style>` 就会造成一次整个页面的重排，所以在初始化时一次性把所有动画的 CSS 都添加进去，导致有大量动画效果时初始化很慢。这个错误的认知也是我当时 Danmaku 没写 CSS 引擎的原因，现在看来或许可以尝试写一下 CSS 引擎，另外 WebGl 引擎我也在考虑，有时间我会去研究一下的。

**Comment by a1018148046** [comment]
坐等作者你继续完善了 我现在写了个油猴子脚本用来播放b站视频了 b站官方那html5播放器好占用资源。。。。
