### ISSUE TITLE
建议加弹幕范围api

### ISSUE THREAD

**Issue by zwjtheone** [weizhenye/Danmaku#31]
建议加弹幕范围api，
全屏、半屏、1/3

**Comment by weizhenye** [comment]
不。建议自己调整 container 大小，然后调用 `resize()`。

**Comment by judgeou** [comment]
> 不。建议自己调整 container 大小，然后调用 `resize()`。

如果只是想让滚动弹幕限制在半屏，调整 container 大小会导致底部弹幕往上抬。

**Comment by weizhenye** [comment]
new 两个 Danmaku，有两个 container，用同一个 video，其中一个 container 专门放底部弹幕
