### ISSUE TITLE
vue  use  Danmaku

### ISSUE THREAD

**Issue by Hxmic** [weizhenye/Danmaku#32]
How  do it?

**Comment by weizhenye** [comment]
https://github.com/ebb-io/ebbx/blob/master/src/components/Danmaku.vue

https://github.com/dd-center/vtbs.moe/blob/master/src/App.vue

**Comment by Hxmic** [comment]
import Danmaku from 'danmaku'

![image](https://user-images.githubusercontent.com/23522154/77603764-e1d0a880-6f4b-11ea-89fd-e20f2d25937a.png)

**Comment by Hxmic** [comment]
引入后会报错。

**Comment by weizhenye** [comment]
在 Nuxt 中需要用 [`<client-only>`](https://nuxtjs.org/api/components-client-only/) 包一下。

**Comment by Hxmic** [comment]
是的。解决了。 在 plugins 中或者直接在 .vue 中
let Danmaku = '';
if (process.client) {
    Danmaku = require('danmaku').default; 
}
export default Danmaku;
