### ISSUE TITLE
怎么进行交互操作？

### ISSUE THREAD

**Issue by xxbld** [weizhenye/Danmaku#33]

**Comment by weizhenye** [comment]
https://zh.wikipedia.org/wiki/%E6%8F%90%E9%97%AE%E7%9A%84%E6%99%BA%E6%85%A7

**Comment by xxbld** [comment]
不好意思！
就是鼠标悬浮时，停住一条弹幕、自定义点赞什么的操作

**Comment by weizhenye** [comment]
目前不支持，你可以尝试自己魔改，使用 render 函数返回自定义节点，绑定上鼠标悬浮事件，强行设置弹幕的位置。

**Comment by s97712** [comment]
授受相关pr吗
