### ISSUE TITLE
高分辨率下,弹幕会抖动

### ISSUE THREAD

**Issue by pslxx** [weizhenye/Danmaku#38]
RT
高分辨率下,弹幕会抖动 移动的不平滑,,,,尤其是多个弹幕并行的时候,
就会出现  A 在B在后,然后又是B在前A在后

**Comment by weizhenye** [comment]
可以描述清楚一点吗？我没有理解你说的现象。

高分辨率是指 Retina 屏？还是说展示弹幕的区域很大？能提供复现方法吗？

**Comment by pslxx** [comment]
能加你QQ或者微信吗?我拍视频给你看

**Comment by weizhenye** [comment]
不能。直接传这里就好。
