### ISSUE TITLE
视频缓冲时弹幕不会暂停

### ISSUE THREAD

**Issue by XcantloadX** [weizhenye/Danmaku#39]
可能会造成弹幕和视频不同步的问题

**Comment by weizhenye** [comment]
https://github.com/weizhenye/Danmaku/blob/ce11135c304e0a53bc2fe38158ca8243646765f3/src/internal/events.js#L10-L12

弹幕的暂停是根据媒体元素的 `pause` 事件来的，理论上缓冲导致的暂停应该也会触发 `pause` 事件，我记得之前是测试过这个场景的。你是什么浏览器？

**Comment by XcantloadX** [comment]
Chrome 85 我是用在油猴脚本里，给其他网站加上B站的弹幕。测试网站用的是 DPlayer+HLS，缓冲时会触发 waiting 事件，貌似不会触发 pause 事件。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zhenye&amp;nbsp;Wei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月19日(星期五) 晚上9:53
收件人:&nbsp;&quot;weizhenye/Danmaku&quot;<Danmaku@noreply.github.com&gt;;
抄送:&nbsp;&quot;XcantloadX&quot;<3188996979@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weizhenye/Danmaku] 视频缓冲时弹幕不会暂停 (#39)

**Comment by weizhenye** [comment]
可能应该用 `playing` 和 `waiting` 这对事件，我测试下。

**Comment by weizhenye** [comment]
已在 `v2.0.2` 中修复
