### ISSUE TITLE
canvas模式下字体就像被砍头了

### ISSUE THREAD

**Issue by a1018148046** [weizhenye/Danmaku#4]
http://i1.piimg.com/4851/43bf2f0d14e51c59.jpg 火狐下
http://i1.piimg.com/4851/b9e1d45fb0342f31.jpg 世界之窗7下
edge下倒是正常

**Comment by weizhenye** [comment]
之前调的时候发现有时候下面会截断，我手欠把 textBaseline 改成 hanging 了，我等会改回 top。

每种字体设置为特定大小后，它们的 line-height 都是不同的，DOM 下会自动计算，Canvas 就没法算了。目前 Canvas 下 line-height 默认为 1.2，应该会满足大多数情况了吧。你也可以自己设置行高，README 里有写。
