### ISSUE TITLE
在视频暂停状态下调用 resize()，弹幕位置不会更新

### ISSUE THREAD

**Issue by XcantloadX** [weizhenye/Danmaku#40]
暂停状态下全屏后，顶部弹幕错位
![Snipaste_2021-02-23_22-48-14](https://user-images.githubusercontent.com/25605245/108861537-4992e600-762a-11eb-8e83-a24233b03fb9.png)

点击播放之后，普通弹幕突然移到最右边，新出现的顶部弹幕位置正确，原有的顶部弹幕仍旧错位
![Snipaste_2021-02-23_22-48-29](https://user-images.githubusercontent.com/25605245/108861653-6e875900-762a-11eb-8bd9-cf56a13f59a8.png)

**Comment by weizhenye** [comment]
暂停后弹幕位置不变，到播放后再更新位置，我觉得没什么问题。

顶部弹幕、底部弹幕在 resize 时位置不更新，已修改。
