### ISSUE TITLE
Danmaku.emit 中 style 参数类型错误

### ISSUE THREAD

**Issue by Wybxc** [weizhenye/Danmaku#43]
现在 `style` 参数的类型为 `CSSStyleDeclaration`，但这一类型不允许缺少其中某些项，导致 typescript 类型错误。

![image](https://user-images.githubusercontent.com/25005856/157023517-853e9acb-6b6c-4288-b0e8-1c6bb6373c3c.png)

**Comment by Wybxc** [comment]
可以考虑使用 [csstype](`https://www.npmjs.com/package/csstype`) 进行类型标注。

**Comment by weizhenye** [comment]
我 TS 写得少，如果引用 `csstype` 的话，是不是意味着所有使用 Danmaku 的人，也需要引用 `csstype` 进行标注类型？如果是这样的话我倾向于不依赖第三方库。

我 TS 写得少，如果改为 `Partial<CSSStyleDeclaration>` 是否能解决这个问题？

**Comment by weizhenye** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1879224/166214885-0c7af7cc-0286-4f82-ba98-8c0143da591c.png">


试了下不报错了，应该这样改可以？
