### ISSUE TITLE
如何设置单个弹幕在屏幕的停留时间？

### ISSUE THREAD

**Issue by judgeou** [weizhenye/Danmaku#45]

**Comment by weizhenye** [comment]
目前不能，有这样的需求？具体什么场景？

**Comment by judgeou** [comment]
> 目前不能，有这样的需求？具体什么场景？

我想用来显示字幕，但是好像超出了范围这个库的使用范围。。。

**Comment by weizhenye** [comment]
如果是 ASS 字幕的话可以看看我的这个库 https://github.com/weizhenye/ASS
