### ISSUE TITLE
弹幕截断

### ISSUE THREAD

**Issue by FlxSNX** [weizhenye/Danmaku#47]
![image](https://user-images.githubusercontent.com/34613385/211187261-efed7a61-a352-4313-971c-44d0121c67be.png)
弹幕容器高度为播放器高度的50%
在全屏后再退出全屏有时会出现弹幕截断的问题，使用的DOM引擎(有调用resize)

**Comment by FlxSNX** [comment]
弹幕很多时 不进行全屏退出全屏，也会出现这种情况
![image](https://user-images.githubusercontent.com/34613385/211316744-50d73cd0-1c78-4ff7-b781-462043b0f1b9.png)

**Comment by weizhenye** [comment]
截断的是不是都是顶部弹幕或底部弹幕？

**Comment by FlxSNX** [comment]
> 截断的是不是都是顶部弹幕或底部弹幕？

容器大小没改变时 截断的都是顶部弹幕或底部弹幕。 大小改变时 从右到左的弹幕也会截断
