### ISSUE TITLE
弹幕重合设定

### ISSUE THREAD

**Issue by gfhfhoo** [weizhenye/Danmaku#48]
目前我是用的是canvas模式+直播，发现如果在某时刻接收的弹幕过多，会造成许多弹幕重合，有什么方法能让其不重合呢？

**Comment by weizhenye** [comment]
没有相关功能，需要自行控制 emit 数量

**Comment by gfhfhoo** [comment]
> 没有相关功能，需要自行控制 emit 数量

谢谢你的回答
