### ISSUE TITLE
关于Canvas和DOM模式下元素高度为0的问题

### ISSUE THREAD

**Issue by gfhfhoo** [weizhenye/Danmaku#49]
环境：
-- Tarui
-- Vue
-- Webkit Macos

在开发环境下，两种模式的弹幕均正常。
在生产环境下，两种模式均出现了问题。
（1）Canvas模式：
```js
<template>
  <div id="danmaku_window"></div>
</template>

<script>
import Danmaku from "danmaku";

export default {
  name: "RollingDanmu",
  data() {
    return {
      danmaku: null,
    }
  },
  mounted() {
    this.danmaku = new Danmaku({
      container: document.getElementById("danmaku_window"),
      engine: "canvas"
    })
  },
  methods: {
    emit: function (msg) {
      // 发射弹幕
      this.danmaku.emit({
        text: msg,
        style: {
          font: '17px sans-serif',
          fillStyle: '#fff',
        }
      })
    }
  }
}
</script>

<style scoped lang="scss">

#danmaku_window {
  width: 480px;
  height: 300px;
  background: green;
}
</style>
```
在上述代码的生产环境中，会导致出现canvas的height=0的情况。
![image](https://user-images.githubusercontent.com/9162454/217853499-f39fc94d-bf7e-44ce-905d-6b65166da5a3.png)

（2）DOM模式：
DOM模式中也会出现类似的问题，所有弹幕的div的translateY均为0。且包装弹幕的div的高度也为0.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/9162454/217853993-d1e6b403-826e-4bba-a44e-210e1062e559.png">

**Comment by weizhenye** [comment]
在 `mounted` 里输出 `#danmaku_window` 的 offsetWidth 和 offsetHeight 看看，然后 nextTick 再看看这两个值

**Comment by gfhfhoo** [comment]
好的，晚些时候会测试一下，目前我的解决方案是用setTimeout一会后再new，这样能够解决。

**Comment by gfhfhoo** [comment]
在不进行nextTick的情况下，height=22，width=500；
在进行nextTick的情况下，height=22，width=500；

**Comment by weizhenye** [comment]
setTimeout 可以解决的话，感觉就是初始化时机问题，DOM 还没准备好，导致高度不对。但是 Vue 的 mounted 应该是确保 DOM 渲染完成的，不知道是不是 Tarui 的问题。

**Comment by gfhfhoo** [comment]
> setTimeout 可以解决的话，感觉就是初始化时机问题，DOM 还没准备好，导致高度不对。但是 Vue 的 mounted 应该是确保 DOM 渲染完成的，不知道是不是 Tarui 的问题。

恩，我目前也就用setTimeout解决了吧。
