### ISSUE TITLE
canvas模式下希望可以让弹幕不置顶 留一段上边距

### ISSUE THREAD

**Issue by a1018148046** [weizhenye/Danmaku#5]
![qq 20160910161624](https://cloud.githubusercontent.com/assets/17643185/18409046/0918f0f8-7772-11e6-8544-c99863744367.jpg)火狐下面的表现是这样的 dom模式下因为设有字体行高 字不是置顶的 但是canvas模式下就不清楚为什么没了上边距

**Comment by weizhenye** [comment]
这个应当由你自己设置。
不知道你这个是什么字体，但我估计在 DOM 下 line-heigh 是大于 1.2 的，在 Canvas 下你可以把行高调大点，canvasStyle 中 font 设为 `20px/1.5 serif` 之类的。
也可以初始化时指定 container，直接给 container 设置边距。

**Comment by a1018148046** [comment]
就是给canvasStyle设定行高还是在顶部。。。。我现在自用方案确实是给container设定了一个内上边距来解决

**Comment by weizhenye** [comment]
我等会把 canvasStyle.textBaseline 改成可以配置。
top 为置顶，middle 为居中，bottom 为置底。
默认 bottom。
