### ISSUE TITLE
两种引擎性能咨询

### ISSUE THREAD

**Issue by gongzhibin** [weizhenye/Danmaku#53]
看到文档里说，canvas引擎更高效，但是消耗内存更大。请问下更高效是指哪个方面？另外想咨询下这两种方案的具体内存及其他方案的对比大概是怎样的？谢谢~

**Comment by weizhenye** [comment]
相同条件 canvas 引擎的 FPS 更高，即它能处理更多的同屏弹幕，上千条弹幕保持 60 FPS 没有问题，DOM 引擎的话上千条会小于 20 FPS。不过通常弹幕数量在没影响阅读的情况下，两种引擎都是远达不到性能上限的，从用户感受上可以说区别不大。

canvas 引擎每条弹幕都是一个画布，所需的内存会比单纯一个 div 要多。具体量级可以自行在 DevTools 的 Performance 测量。
