### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by a1018148046** [weizhenye/Danmaku#8]
每个弹幕的运动时间和运动距离一般都不会变 可以在runningList的cmt对象里面把位置和每次移动的距离弄进去 然后每次动画把位置减去每次移动的距离就行了 说不定能提升性能 也可以在cmt对象里面把存活时间缓存进去 总之就是把每次动画时做的运算减少。。。。

**Comment by a1018148046** [comment]
刚刚自己试了一下 cpu占用没多少变化 肉眼感受的帧数倒是高了。。。。旧方案偶尔弹幕会跳一下 这方案丝般顺滑

**Comment by weizhenye** [comment]
你描述的算法和目前采用的有区别？就是 `var totalWidth = this.width + cmt.width;` 这行把 totalWidth 缓存？存活时间 `this.duration` 缓存到 cmt 里？

**Comment by a1018148046** [comment]
就是把每次移动的距离给缓存 你可以去试试 `var canvasEngine = function() {
  while (this.position < this.comments.length) {
    cmt = this.comments[this.position];
    cmtt = this._hasMedia ? cmt.time : cmt._utc;
    if (cmtt >= ct) {
      break;
    }
    cmt._utc = Date.now() / 1000;
    cmt.canvas = createCommentCanvas(cmt);
    cmt.y = allocate.call(this, cmt);
    if (cmt.mode === 'top' || cmt.mode === 'bottom') {
      cmt.x = (this.width - cmt.width) >> 1;
    }
    cmt.fuck = this.width + cmt.width;
    cmt.fuck2 = 1.7;
    this.runningList.push(cmt);
    ++this.position;
  }
  var len = this.runningList.length;
  for (i = 0; i < len; i++) {
    cmt = this.runningList[i];
    var totalWidth = this.width + cmt.width;
    var elapsed = totalWidth * (dn - cmt._utc) * pbr / this.duration;
    if (cmt.mode === 'rtl') {
      cmt.x = cmt.fuck;
      cmt.fuck = cmt.fuck - cmt.fuck2;
    }
    this.stage.context.drawImage(cmt.canvas, cmt.x, cmt.y);
  }
}` 我粗略这么做了一下 弹幕滚动顺滑不少

**Comment by weizhenye** [comment]
每帧移动的距离是不确定的。每秒多少帧是根据设备和当前 CPU 使用来决定的，就像 144Hz 的屏幕和 60Hz 的屏幕肯定不一样。
另外这种方案在调用 resize API 时会比较麻烦。
纯 JavaScript 计算部分的耗时其实是非常少的，与 drawImage 或 translate 等会产生 reflow 和 repaint 的方法比起来完全不值一提。

**Comment by a1018148046** [comment]
那这就尴尬了 能不能默认显示器都为60帧 让使用者指定speed

**Comment by weizhenye** [comment]
在追求性能之前，首先要「表现正确」。这也不仅仅是屏幕的问题，同屏很多弹幕的情况下，性能可能会降到 30fps，浏览器调用 rAF 的间隔是未知的，指定距离或速度都会导致错误的结果。
就你改动的部分，这里纯 JavaScript 计算最耗时的应该是 elapsed，你都没注释掉，这不是计算量导致的性能提升。
你所说的顺滑，我猜应该是 `(this.width - elapsed + .5) | 0` 这里，我做了取整处理，导致小数部分的变动没有体现出来。这样写考虑到的是 drawImage 绘制小数坐标时会有较大的性能损失，当然你测试时弹幕量少的话体现不出来，对于单条弹幕来说用小数绘制可能会变得「顺滑」。
