### ISSUE TITLE
同行弹幕 后来的弹幕宽度比之前的宽 导致滚动中这俩弹幕可能重叠在一起

### ISSUE THREAD

**Issue by a1018148046** [weizhenye/Danmaku#9]
![qq 20161208003251](https://cloud.githubusercontent.com/assets/17643185/20976573/e298e36e-bcdd-11e6-9971-f6c658e5b5fb.jpg)

**Comment by weizhenye** [comment]
请提供一下复现数据。

**Comment by a1018148046** [comment]
[新建文本文档.txt](https://github.com/weizhenye/Danmaku/files/639674/default.txt)

**Comment by 303182519** [comment]
我觉得是个正常的效果吧，可以叠加，就是当面的那一条的宽度比较宽，速度比较快，然后追上去
